[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8.0"
futures = "0.3.30"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
tokio = { version = "1.39.2", features = ["full"] }
tokio-tungstenite = "0.23.1"
toml = "0.8.19"
