[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8.0"
futures-channel = "0.3.30"
tokio = { version = "1.39.2", features = ["full"] }
tokio-tungstenite = "0.23.1"
