[package]
name = "agent"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
reqwest = { version = "0.12.5", features = ["blocking", "json"] }
serde = { version = "1.0.205", features = ["derive"] }
serde_json = "1.0.122"
socket2 = "0.5.7"
